### ISSUE TITLE
LDL reproduce issues

### ISSUE THREAD

**Issue by yuanzhongshang** [xinhe-lab/ctwas-paper#1]
Hi, 

I want to reproduce the result of LDL in the cTWAS paper following https://github.com/xinhe-lab/ctwas-paper/blob/main/application/LDL/run_LDL.R. However, I'm encountering some unclear issues.

1.  I've downloaded the GWAS summary statistics ukb-d-30780_irnt with HG19. Do I need to perform any steps to convert from HG19 to HG38 before using these summary statistics? It appears that these statistics are directly used in the cTWAS analysis.
2.  I notice the directory /project2/mstephens/wcrouse/UKB_LDR_0.1 includes the in-sample LD matrix. Can I find it at  https://uchicago.app.box.com/s/jqocacd2fulskmhoqnasrknbt59x3xkn/folder/234628840317?
3. I'm having trouble downloading the file 'gtex_v8_expression_mashr_snp_smultixcan_covariance.txt.gz' from  https://predictdb.org/post/2021/07/21/gtex-v8-models-on-eqtl-and-sqtl/.Could you provide guidance on accessing this file?

Thanks in advance for your assistance!

Best,
Zhongshang

**Comment by sq-96** [comment]
Hi Zhongshang,

1. No you don't need to convert. We match SNPs by rsid instead of genomic coordinates. 
2. We sampled a certain number of UKB individuals to precompute LD matrices. UKB_LDR_0.1 means 10% of UKB individuals if I remember. 
3. Go to this website: https://predictdb.org/post/2021/07/21/gtex-v8-models-on-eqtl-and-sqtl/. Right click the link for gtex_v8_expression_mashr_snp_smultixcan_covariance.txt.gz and select download linked file. 

Best,
Sheng

**Comment by yuanzhongshang** [comment]
Hi Sheng,

Thank you for your reply.

Best,
Zhongshang
